### PR TITLE
Contains exactly in any order, Vavr version

### LINKED ISSUE #96: `containsExactlyInAnyOrder` doesn't accept vavr `Seq` or `Set`
The following will emit a compilation error:

```
final Array<Integer> actual = Array.of(0);
final Array<Integer> expected = Array.of(0);

VavrAssertions.assertThat(actual).containsExactlyInAnyOrder(expected);
```

The argument to `containsExactlyInAnyOrder` requires a Java array so the above would currently have to be written as `assertThat(actual).containsExactlyInAnyOrder(expected.toJavaArray(Integer[]::new))`.

The former is much more fluent and less boilerplatey, though.

### PR DESCRIPTION
**Pull request by mchmielarz**
Fixes #96

### CODE REVIEW

**Review by Opalo — APPROVED** [review]

**Comment by mchmielarz** [comment]
@pivovarit Could you look at it?

**Comment by mchmielarz** [comment]
@pivovarit ping

**Review by pivovarit — APPROVED** [review]

**Comment by sullis** [comment]
when will you be able to release the next version of assertj-vavr ?

**Comment by mchmielarz** [comment]
Just after finalizing #97.  I'll try to sit down with this on weekend.

**Pull request merged**
