### PR TITLE
Removes warning from pom.xml

### LINKED ISSUE #105: Remove warnings from pom.xml

### PR DESCRIPTION
**Pull request by mchmielarz**
Closes #105

### CODE REVIEW

**Comment by pivovarit** [comment]
What was the warning? it might have been taken care of already

**Comment by mchmielarz** [comment]
It was fixing
- complaining about the missing version of gpg plugin,
- duplicated entry for junit dependency,
- and no explicit definition of sources encoding.
The only junit case remained from them. I would merge it

**Comment by mchmielarz** [comment]
@pivovarit approve?

**Review by pivovarit — APPROVED** [review]

**Comment by sullis** [comment]
@mchmielarz  @pivovarit  Can you release a new version of assertj-vavr?  The last release was in December 2019.

**Comment by sullis** [comment]
ping @mchmielarz  @pivovarit 

> @mchmielarz @pivovarit Can you release a new version of assertj-vavr? The last release was in December 2019.

**Comment by pivovarit** [comment]
@mchmielarz let's release it?

**Comment by mchmielarz** [comment]
@sullis @pivovarit Released. I had issues with gpg keys but finally worked. v0.3.0

**Pull request merged**
